# Generated by Django 3.2.12 on 2022-03-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_project',
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo'
        ),
    ]
