# Generated by Django 3.2.12 on 2022-03-06 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0002_auto_20220306_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name_project',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
