# Generated by Django 3.2.12 on 2022-03-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_project_name_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['id']},
        ),
    ]
